apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: nodejs-pipeline-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: nodejs-pipeline
  params:
    - name: "source-repo"
      value: "https://github.com/nhoomtham/express-sample-app"
    - name: "image-repo"
      value: "quay.io/nhoomtham_aff/express-sample-app"
  workspaces:
    - name: pipeline-shared-data
      persistentVolumeClaim:
        claimName: pvc-pipeline-npm-test-buildah
